# k8s/namespace-and-rbac.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: qa-tests
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-runner
  namespace: qa-tests
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-executor
  namespace: qa-tests
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create","get","list","watch","delete"]
  - apiGroups: [""]
    resources: ["pods","pods/log"]
    verbs: ["get","list","watch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-runner-binding
  namespace: qa-tests
subjects:
  - kind: ServiceAccount
    name: jenkins-runner
    namespace: qa-tests
roleRef:
  kind: Role
  name: job-executor
  apiGroup: rbac.authorization.k8s.io
